name: Python Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install boto3 pandas
      - name: Run Scripts
        run: |
          python list_s3_buckets.py
          python analyze_csv.py
